spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/panchalravi/config-repo
          default-label: main
          force-pull: true
          timeout: 5
          clone-on-start: true
server:
  port: 8888